name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # ou main, se for o caso

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ğŸ” Etapa de autenticaÃ§Ã£o separada
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # â˜ï¸ ConfiguraÃ§Ã£o do SDK GCloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ğŸ› ï¸ Build da imagem e envio para o Container Registry
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app

      # ğŸš€ Deploy da imagem no Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
